### ISSUE TITLE
Unnecessary font face declaration?

### ISSUE THREAD

**Issue by loker** [voidlabs/versafix-template#13]
https://github.com/voidlabs/mosaico/blob/6225f4d1a2056fced024d185c493c9aafc18d589/templates/versafix-1/template-versafix-1.html#L606

Hi, I'm trying to create a new template and I'm using the versafix as a base/learning template. I noticed that some of the links of the images have font preferences even though they don't have any text content in the output. Maybe clearing these unused parts would be useful... Or am I missing something? :)

**Comment by loker** [comment]
Hi sorry for the wrong place. I was asking about the font variables for img tag, not the size variables. I understand that using the font variables help shaping the alt text styling, but using the same classes with paragraphs (longtextstyle) seemed a bit off to me. Maybe we could declare alttextstyle too if using dynamic styling for alt text in img tag is useful.

I've stuck on this, as when I want to change the default font face for longtext I have to deal with the img tags too, otherwise ko engine is trying to overwrite I think (sorry I really don't know anything about ko, but trying to understand from js console...)

**Comment by bago** [comment]
I don't understand why you care about this. What's wrong with sharing the same style with the paragraphs? The alt text will be shown in the same place where paragraphs are shown. I don't think that we need one more style for that.

If you want to alter the versafix in an easy way, look at this repository source code and what htmml is and how it works. It will be easier to maintain a complex layout and make sure to use the same value for the same styles everywhere you use it.

If you want to introduce an altTextStyle you can do that, of course. Mosaico is cool because the library itself is not biased: the master template declares the html and what can be edited and how, and you can change the master template without altering the mosaico library.

**Comment by loker** [comment]
I encounter the issue when I was trying to change the default typeface for paragraphs (longtext in template term) and couldn't succeed until I changed the alt text attributes as well. As alt text and p text are two very different elements, I wanted to offer an alternative... That's all, sorry if I wasted your time.

I've added a new class for paragraphs with serif typefaces, I'm already quite happy with my solution. Thanks for the great tool that I could do it. Works like a charm.

**Comment by bago** [comment]
no problem. You can change it. IMO it is right to reuse paragraph styles for the ALT text. 99% of people don't even care about ALT styling (and many clients don't obey to font styling for ALTs), so I think showing one more styling option would only confuse them. IMO this is one of the cases where "less is more", a lot more.

That's said, the good thing in Mosaico is that you can simply create your own versafix-based master template and add your own custimizability to your own preferences!

I didn't waste time: I simply explained why I won't take your submittion as a "bug report" and that it won't be "fixed" in a future release on versafix-1. English is not my first language.
