### ISSUE TITLE
Background Images in Blocks/templates

### ISSUE THREAD

**Issue by pbatroff** [voidlabs/versafix-template#21]
is it possible to add background images to a template? I found [this](https://github.com/voidlabs/mosaico/issues/431) issue, that seems to imply it should be possible, but I am not sure where to add code to be able to reproduce this. 

Is it possible to add an image picker to the template, and define a background image for either blocks or the whole template?

**Comment by bago** [comment]
Mosaico 0.18.5 includes a "src" widget to pick non <img> images in the content/style tab. So you can create templates using background images.

Versafix-1 does not support background images because they don't have good email client support (see Outlook/Window 10-11 Mail) and we prefer to stick with broad compatibility.
